### ISSUE TITLE
bcrypt.kdf() does not actually use bcrypt

### ISSUE THREAD

**Issue by lgommans** [pyca/bcrypt#103]
When calling `bcrypt.kdf(...)`, the library doesn't use bcrypt. The documentation I've been able to find (the readme in this repository and [on pypi](https://pypi.python.org/pypi/bcrypt/3.1.2)) is extremely brief, but from tests I noticed it must use a completely different algorithm, which is confirmed by reading the source code.

One of bcrypt's (arguable) improvements over the older pbkdf2, is that the cost is logarithmic rather than linear. It makes a lot more sense to type 11 in your code and upgrade it to 12 at some point, compared to working with numbers like 1000000.

When using `bcrypt.kdf` however, the bcrypt library actually calls pbkdf2 under the hood, where rounds=10 would be useless and dangerous. Any developer reading this code would expect it to use bcrypt as a KDF.

I saw in an old Github Issue in this repository that it was added for compatibility. Renaming the function to clear things up (or just moving it to a different repository, since it has nothing to do with bcrypt whatsoever) is probably a no-go. Rather I'd suggest something like: during a grace period, print a warning to stderr when the function is called with rounds less than, say, 100; then in a future release a year later, throw an exception when it happens.

**Comment by reaperhulk** [comment]
As you noted, it was added for compatibility, but also to allow users to do OpenSSH private key encryption (#56). The bcrypt_pbkdf is *almost* pbkdf2, but changes a few small details and uses a "bcrypt hash" (see: https://github.com/pyca/bcrypt/blob/master/src/_csrc/bcrypt_pbkdf.c#L29-L49).

So it isn't using bcrypt the KDF, but it is using the expanded blowfish key schedule. Blame OpenBSD 😄. I definitely agree that we should document this function much better and steer users away from it since it is of limited utility unless you're looking for compatibility with OpenSSH private key encryption. A warning on low iteration count is probably also a good idea in general and I'd be happy to review a PR if you're interested in submitting one!

**Comment by lgommans** [comment]
> I'd be happy to review a PR if you're interested in submitting one!

Sure, it doesn't sound like much work. Would you say a warning (to sys.stderr) is better or should it throw an exception (since it shouldn't happen: any code doing that is broken crypto)?

**Comment by reaperhulk** [comment]
I think a warning is appropriate. I'm concerned about using an exception because if a user has a pre-existing openssh key then deriving the key using `bcrypt.kdf` should not fail even if their iteration count was unwisely low.

**Comment by lgommans** [comment]
Fixed in pull request #104
