### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ffi'

### ISSUE THREAD

**Issue by archienorman11** [pyca/bcrypt#105]
Can anyone help shed some light on this error? I dont experience any issues if I run my application locally or on a Ubuntu Instance. However, when deploying via AWS Beanstalk I get this error.

```
File "/opt/python/run/venv/lib64/python2.7/site-packages/bcrypt/__init__.py", line 82, in hashpw
hashed = _bcrypt.ffi.new("char[]", 128)
AttributeError: 'module' object has no attribute 'ffi'
```

Any suggestion much appreciated.

FYI - I have `bcrypt==3.1.2` installed.

**Comment by alichaudry** [comment]
@archienorman11 I'm definitely not an expert in this, but it seems like you might be missing CFFI on the AWS Beanstalk container. CFFI is the C Foreign Function Interface, which lets you run C code from Python. Since bcrypt is primarily implemented in C, that might be the issue (although I'll let the authors or someone more knowledgeable speak to this).

I'm also not familiar with AWS Beanstalk, but perhaps those boxes are missing C compilers and/or C compatibility with Python?

**Comment by reaperhulk** [comment]
I don't know enough about how EBS works to provide a good answer here. That error definitely makes it look like it failed to compile or cffi is unavailable though.

**Comment by reaperhulk** [comment]
Closing since this is unlikely to be a bug in bcrypt but rather an issue with deployment in a semi-unusual environment.
