### ISSUE TITLE
get the ValueError ("Invalid salt") while checking for encrypted passwords and passwords

### ISSUE THREAD

**Issue by mmdbalkhi** [pyca/bcrypt#329]
In Flask, I use this library to encrypt user passwords and store them in a database, but I see some errors. My code when encrypting is:

```python
import bcrypt

def string_to_bytes(string: str) -> bytes:
    return bytes(string, "utf-8")


def string_to_hash(string: str) -> bytes:
    return bcrypt.hashpw(string_to_bytes(string), bcrypt.gensalt()).decode("utf-8")


def check_password_hash(password: str, hash: bytes) -> bool:
    if not (password or hash):
        return
    return bcrypt.checkpw(string_to_bytes(password), string_to_bytes(hash))

```

error:

```python
  File "/home/mmdbalkhi/w/breeze/breeze/models.py", line 95, in check_password
    return utils.check_password_hash(self.password, password)
  File "/home/mmdbalkhi/w/breeze/breeze/utils.py", line 52, in check_password_hash
    return bcrypt.checkpw(string_to_bytes(password), string_to_bytes(hash))
  File "/home/mmdbalkhi/w/breeze/venv/lib/python3.10/site-packages/bcrypt/__init__.py", line 124, in checkpw
    ret = hashpw(password, hashed_password)
  File "/home/mmdbalkhi/w/breeze/venv/lib/python3.10/site-packages/bcrypt/__init__.py", line 104, in hashpw
    raise ValueError("Invalid salt")
ValueError: Invalid salt
```

I have seen in some places that the problem may be encoding to `utf-8`, but what should use instead?

**Comment by reaperhulk** [comment]
The hash is ascii, which can be encoded/decoded via utf8. That said, you should just store it as native bytes in your DB so you don't need to do encoding at all.

Your issue is something to do with the code you're using to store/load the hash itself and not an issue in `bcrypt`. The code you're showing already appears to have typing issues in that `check_password_hash` claims `hash` is bytes, but then passes it to `string_to_bytes` which takes `str` (and will fail if a non-string is provided with a `TypeError`). You should simplify your invocations until the problem goes away and use that to isolate the part of your system that is causing the encoding issues.
