### ISSUE TITLE
Provide wheels for Python 3.5

### ISSUE THREAD

**Issue by agronholm** [pyca/bcrypt#54]
A Windows user on #python asked why they can't install bcrypt. The missing wheels are the reason.

**Comment by alex** [comment]
@reaperhulk this looks like it needs to be added to the builder: https://jenkins.cryptography.io/job/bcrypt-wheel-builder/ not sure what's involved with that?

(Is there a way we can reduce duplication with the other wheel builder jobs?)

**Comment by refringe** [comment]
+1

**Comment by Vesuvium** [comment]
+1

**Comment by gdude2002** [comment]
Any progress on this? Us Windows users are having a hard time.

**Comment by AzureusNation** [comment]
@alex @reaperhulk Would appreciate if there is any u[date on this as python 3.5 has been out for a while and I would like to use Flask-Bcrypt but cant at the moment as I'm on windows :+1:

**Comment by agronholm** [comment]
It's been almost three months and nothing has been done. Do any of the devs even care?

**Comment by alex** [comment]
Nope! Not even a little bit.

(While I'm sorry we haven't gotten around to this, you're being an asshole and doing nothing to make me want to prioritize working on this. In the future you might consider adopting a less entitled attitude.)

**Comment by AzureusNation** [comment]
@alex I see there is a nice PR #51, whats the likely hood you could maybe merge maybe now? :3 pretty please and maybe add it to Jenkins... pretty please with a  cherry on top :smile:

**Comment by agronholm** [comment]
I realize that F/OSS developers sometimes have other priorities (being one myself), but leaving a comment takes less than a minute. That at least would indicate that someone intends to fix the problem and would make waiting a whole lot easier. This comment is directed at @reaperhulk since he has not commented on the issue in these three months, and judging by your first comment, @alex, you don't seem to have the necessary privileges to fix the Jenkins configuration.

It's frustrating that a simple task as this is being left undone for months because nobody with the free time and the ability has the privileges to do anything about it.

**Comment by alex** [comment]
Wheels have been uploaded.

**Comment by agronholm** [comment]
Thank you.

**Comment by reaperhulk** [comment]
In this particular case the task fell through the cracks, although I'm not entirely sure how as I am subscribed to this issue but don't recall ever seeing this before now...

I don't mind being pinged occasionally for tasks since if I don't remember to put them on a todo list they might be entirely forgotten. However, the accusation that we don't care is a dangerous one as there are many non-malicious explanations for tasks remaining incomplete.

My colleague was more direct than I would have been (although responses to provocative things are always mood dependent), but having been on both sides of this situation I sympathize both with overworked/under-appreciated maintainers as well as those who grow frustrated seeing simple tasks remain incomplete for months.

Unfortunately, the reality of open source maintenance means situations like this will certainly recur in the future. Hopefully we can do better next time.

**Comment by agronholm** [comment]
Thank you for your response. I admit to being overly provocative in my attempt to get the maintainers' attention, but it (unfortunately) has proven in practice to be the quickest way to get the ball rolling, at the cost of some negative karma. It sure works on me when I'm on the other side of the fence.

**Comment by refringe** [comment]
Thanks guys!
