### ISSUE TITLE
Add bcrypt_pbkdf ?

### ISSUE THREAD

**Issue by mchlt** [pyca/bcrypt#56]
py-bcrypt 0.4 had the `bcrypt_pbkdf` key derivation function which no other Python module appears to have. since you claim compatibility with py-bcrypt ... :)   nudge nudge

OpenSSH uses it when encrypting their new private key format, hence paramiko needs it to read those.
found an example here:
https://github.com/grnet/python-bcrypt

**Comment by reaperhulk** [comment]
Since OpenSSH is using it I think having `bcrypt_pbkdf` makes sense. I'll look into adding it.

**Comment by danstender** [comment]
Great! :+1: 
We have recursive problems with asyncssh: https://bugs.debian.org/824952, that would fix it.

**Comment by ronf** [comment]
As a workaround for now, I've changed AsyncSSH to disable its use of bcrypt if it finds that the version installed doesn't contain a kdf() function.

Adding support for kdf() which is backward compatible with py-bcrypt would be greatly appreciated!

**Comment by reaperhulk** [comment]
This has been added in the upcoming 3.0.0 version that will be released today.

**Comment by danstender** [comment]
Very great! Thank you very much.

Best,
DS


-- 
4096R/DF5182C8
http://www.danielstender.com/blog/

**Comment by ronf** [comment]
Yes - much appreciated! I just tested AsyncSSH against this and it works great. The current version of AsyncSSH should automatically enable its bcrypt-related functionality when this version of bcrypt is installed.

I'll be checking in a change to have setup.py there depend on this rather than the older py-bcrypt now that this is available. Thanks!

**Comment by mchlt** [comment]
Great! :+1:
